version: '3'

services:
  frontend:
    build: ./frontend
    container_name: todo-app-frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_BASE_URL=http://localhost:8000  # Ensure it's set like this
    networks:
      - todo-app-network

  backend:
    build: ./backend
    container_name: todo-app-backend
    ports:
      - "8000:8000"
    networks:
      - todo-app-network  # Both services should be on the same network

    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Aa123456
      POSTGRES_DB: postgres
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - todo-app-network
    restart: always

networks:
  todo-app-network:
    driver: bridge  # Use bridge network for communication between containers