version: "3.8"
services:
  frontend:
    image: front:api_url_localhost
    ports:
      - "80:80"
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Aa123456
      POSTGRES_DB: postgres
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    restart: always